package com.jfl.pas2.mapper;

import com.jfl.pas2.domain.Detail;
import com.jfl.pas2.domain.DetailExample;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
@Mapper
public interface DetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail
     *
     * @mbggenerated Wed Aug 11 21:50:55 CST 2021
     */
    int deleteByPrimaryKey(String serialNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail
     *
     * @mbggenerated Wed Aug 11 21:50:55 CST 2021
     */
    int insert(Detail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail
     *
     * @mbggenerated Wed Aug 11 21:50:55 CST 2021
     */
    int insertSelective(Detail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail
     *
     * @mbggenerated Wed Aug 11 21:50:55 CST 2021
     */
    List<Detail> selectByExample(DetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail
     *
     * @mbggenerated Wed Aug 11 21:50:55 CST 2021
     */
    Detail selectByPrimaryKey(String serialNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail
     *
     * @mbggenerated Wed Aug 11 21:50:55 CST 2021
     */
    int updateByPrimaryKeySelective(Detail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail
     *
     * @mbggenerated Wed Aug 11 21:50:55 CST 2021
     */
    int updateByPrimaryKey(Detail record);
}