
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ohmygoal
    username: root
    password: ohmygoal
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /jsp/
      suffix: .jsp

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.jfl.pas2.domain

server:
  servlet:
    context-path: /pas2
    jsp:
      init-parameters:
        development : true
