package com.jfl.pas2.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class ProductExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbggenerated Fri Jul 30 21:01:06 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbggenerated Fri Jul 30 21:01:06 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbggenerated Fri Jul 30 21:01:06 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Fri Jul 30 21:01:06 CST 2021
     */
    public ProductExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Fri Jul 30 21:01:06 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Fri Jul 30 21:01:06 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Fri Jul 30 21:01:06 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Fri Jul 30 21:01:06 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Fri Jul 30 21:01:06 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Fri Jul 30 21:01:06 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Fri Jul 30 21:01:06 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Fri Jul 30 21:01:06 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Fri Jul 30 21:01:06 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Fri Jul 30 21:01:06 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbggenerated Fri Jul 30 21:01:06 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andProductModelIdIsNull() {
            addCriterion("product_model_id is null");
            return (Criteria) this;
        }

        public Criteria andProductModelIdIsNotNull() {
            addCriterion("product_model_id is not null");
            return (Criteria) this;
        }

        public Criteria andProductModelIdEqualTo(String value) {
            addCriterion("product_model_id =", value, "productModelId");
            return (Criteria) this;
        }

        public Criteria andProductModelIdNotEqualTo(String value) {
            addCriterion("product_model_id <>", value, "productModelId");
            return (Criteria) this;
        }

        public Criteria andProductModelIdGreaterThan(String value) {
            addCriterion("product_model_id >", value, "productModelId");
            return (Criteria) this;
        }

        public Criteria andProductModelIdGreaterThanOrEqualTo(String value) {
            addCriterion("product_model_id >=", value, "productModelId");
            return (Criteria) this;
        }

        public Criteria andProductModelIdLessThan(String value) {
            addCriterion("product_model_id <", value, "productModelId");
            return (Criteria) this;
        }

        public Criteria andProductModelIdLessThanOrEqualTo(String value) {
            addCriterion("product_model_id <=", value, "productModelId");
            return (Criteria) this;
        }

        public Criteria andProductModelIdLike(String value) {
            addCriterion("product_model_id like", value, "productModelId");
            return (Criteria) this;
        }

        public Criteria andProductModelIdNotLike(String value) {
            addCriterion("product_model_id not like", value, "productModelId");
            return (Criteria) this;
        }

        public Criteria andProductModelIdIn(List<String> values) {
            addCriterion("product_model_id in", values, "productModelId");
            return (Criteria) this;
        }

        public Criteria andProductModelIdNotIn(List<String> values) {
            addCriterion("product_model_id not in", values, "productModelId");
            return (Criteria) this;
        }

        public Criteria andProductModelIdBetween(String value1, String value2) {
            addCriterion("product_model_id between", value1, value2, "productModelId");
            return (Criteria) this;
        }

        public Criteria andProductModelIdNotBetween(String value1, String value2) {
            addCriterion("product_model_id not between", value1, value2, "productModelId");
            return (Criteria) this;
        }

        public Criteria andProductTypeIsNull() {
            addCriterion("product_type is null");
            return (Criteria) this;
        }

        public Criteria andProductTypeIsNotNull() {
            addCriterion("product_type is not null");
            return (Criteria) this;
        }

        public Criteria andProductTypeEqualTo(String value) {
            addCriterion("product_type =", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeNotEqualTo(String value) {
            addCriterion("product_type <>", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeGreaterThan(String value) {
            addCriterion("product_type >", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeGreaterThanOrEqualTo(String value) {
            addCriterion("product_type >=", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeLessThan(String value) {
            addCriterion("product_type <", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeLessThanOrEqualTo(String value) {
            addCriterion("product_type <=", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeLike(String value) {
            addCriterion("product_type like", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeNotLike(String value) {
            addCriterion("product_type not like", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeIn(List<String> values) {
            addCriterion("product_type in", values, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeNotIn(List<String> values) {
            addCriterion("product_type not in", values, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeBetween(String value1, String value2) {
            addCriterion("product_type between", value1, value2, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeNotBetween(String value1, String value2) {
            addCriterion("product_type not between", value1, value2, "productType");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNull() {
            addCriterion("product_name is null");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNotNull() {
            addCriterion("product_name is not null");
            return (Criteria) this;
        }

        public Criteria andProductNameEqualTo(String value) {
            addCriterion("product_name =", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotEqualTo(String value) {
            addCriterion("product_name <>", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThan(String value) {
            addCriterion("product_name >", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThanOrEqualTo(String value) {
            addCriterion("product_name >=", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLessThan(String value) {
            addCriterion("product_name <", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLessThanOrEqualTo(String value) {
            addCriterion("product_name <=", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLike(String value) {
            addCriterion("product_name like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotLike(String value) {
            addCriterion("product_name not like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameIn(List<String> values) {
            addCriterion("product_name in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotIn(List<String> values) {
            addCriterion("product_name not in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameBetween(String value1, String value2) {
            addCriterion("product_name between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotBetween(String value1, String value2) {
            addCriterion("product_name not between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andProductBrandIsNull() {
            addCriterion("product_brand is null");
            return (Criteria) this;
        }

        public Criteria andProductBrandIsNotNull() {
            addCriterion("product_brand is not null");
            return (Criteria) this;
        }

        public Criteria andProductBrandEqualTo(String value) {
            addCriterion("product_brand =", value, "productBrand");
            return (Criteria) this;
        }

        public Criteria andProductBrandNotEqualTo(String value) {
            addCriterion("product_brand <>", value, "productBrand");
            return (Criteria) this;
        }

        public Criteria andProductBrandGreaterThan(String value) {
            addCriterion("product_brand >", value, "productBrand");
            return (Criteria) this;
        }

        public Criteria andProductBrandGreaterThanOrEqualTo(String value) {
            addCriterion("product_brand >=", value, "productBrand");
            return (Criteria) this;
        }

        public Criteria andProductBrandLessThan(String value) {
            addCriterion("product_brand <", value, "productBrand");
            return (Criteria) this;
        }

        public Criteria andProductBrandLessThanOrEqualTo(String value) {
            addCriterion("product_brand <=", value, "productBrand");
            return (Criteria) this;
        }

        public Criteria andProductBrandLike(String value) {
            addCriterion("product_brand like", value, "productBrand");
            return (Criteria) this;
        }

        public Criteria andProductBrandNotLike(String value) {
            addCriterion("product_brand not like", value, "productBrand");
            return (Criteria) this;
        }

        public Criteria andProductBrandIn(List<String> values) {
            addCriterion("product_brand in", values, "productBrand");
            return (Criteria) this;
        }

        public Criteria andProductBrandNotIn(List<String> values) {
            addCriterion("product_brand not in", values, "productBrand");
            return (Criteria) this;
        }

        public Criteria andProductBrandBetween(String value1, String value2) {
            addCriterion("product_brand between", value1, value2, "productBrand");
            return (Criteria) this;
        }

        public Criteria andProductBrandNotBetween(String value1, String value2) {
            addCriterion("product_brand not between", value1, value2, "productBrand");
            return (Criteria) this;
        }

        public Criteria andProductSizeIsNull() {
            addCriterion("product_size is null");
            return (Criteria) this;
        }

        public Criteria andProductSizeIsNotNull() {
            addCriterion("product_size is not null");
            return (Criteria) this;
        }

        public Criteria andProductSizeEqualTo(String value) {
            addCriterion("product_size =", value, "productSize");
            return (Criteria) this;
        }

        public Criteria andProductSizeNotEqualTo(String value) {
            addCriterion("product_size <>", value, "productSize");
            return (Criteria) this;
        }

        public Criteria andProductSizeGreaterThan(String value) {
            addCriterion("product_size >", value, "productSize");
            return (Criteria) this;
        }

        public Criteria andProductSizeGreaterThanOrEqualTo(String value) {
            addCriterion("product_size >=", value, "productSize");
            return (Criteria) this;
        }

        public Criteria andProductSizeLessThan(String value) {
            addCriterion("product_size <", value, "productSize");
            return (Criteria) this;
        }

        public Criteria andProductSizeLessThanOrEqualTo(String value) {
            addCriterion("product_size <=", value, "productSize");
            return (Criteria) this;
        }

        public Criteria andProductSizeLike(String value) {
            addCriterion("product_size like", value, "productSize");
            return (Criteria) this;
        }

        public Criteria andProductSizeNotLike(String value) {
            addCriterion("product_size not like", value, "productSize");
            return (Criteria) this;
        }

        public Criteria andProductSizeIn(List<String> values) {
            addCriterion("product_size in", values, "productSize");
            return (Criteria) this;
        }

        public Criteria andProductSizeNotIn(List<String> values) {
            addCriterion("product_size not in", values, "productSize");
            return (Criteria) this;
        }

        public Criteria andProductSizeBetween(String value1, String value2) {
            addCriterion("product_size between", value1, value2, "productSize");
            return (Criteria) this;
        }

        public Criteria andProductSizeNotBetween(String value1, String value2) {
            addCriterion("product_size not between", value1, value2, "productSize");
            return (Criteria) this;
        }

        public Criteria andProductColorIsNull() {
            addCriterion("product_color is null");
            return (Criteria) this;
        }

        public Criteria andProductColorIsNotNull() {
            addCriterion("product_color is not null");
            return (Criteria) this;
        }

        public Criteria andProductColorEqualTo(String value) {
            addCriterion("product_color =", value, "productColor");
            return (Criteria) this;
        }

        public Criteria andProductColorNotEqualTo(String value) {
            addCriterion("product_color <>", value, "productColor");
            return (Criteria) this;
        }

        public Criteria andProductColorGreaterThan(String value) {
            addCriterion("product_color >", value, "productColor");
            return (Criteria) this;
        }

        public Criteria andProductColorGreaterThanOrEqualTo(String value) {
            addCriterion("product_color >=", value, "productColor");
            return (Criteria) this;
        }

        public Criteria andProductColorLessThan(String value) {
            addCriterion("product_color <", value, "productColor");
            return (Criteria) this;
        }

        public Criteria andProductColorLessThanOrEqualTo(String value) {
            addCriterion("product_color <=", value, "productColor");
            return (Criteria) this;
        }

        public Criteria andProductColorLike(String value) {
            addCriterion("product_color like", value, "productColor");
            return (Criteria) this;
        }

        public Criteria andProductColorNotLike(String value) {
            addCriterion("product_color not like", value, "productColor");
            return (Criteria) this;
        }

        public Criteria andProductColorIn(List<String> values) {
            addCriterion("product_color in", values, "productColor");
            return (Criteria) this;
        }

        public Criteria andProductColorNotIn(List<String> values) {
            addCriterion("product_color not in", values, "productColor");
            return (Criteria) this;
        }

        public Criteria andProductColorBetween(String value1, String value2) {
            addCriterion("product_color between", value1, value2, "productColor");
            return (Criteria) this;
        }

        public Criteria andProductColorNotBetween(String value1, String value2) {
            addCriterion("product_color not between", value1, value2, "productColor");
            return (Criteria) this;
        }

        public Criteria andProductBladeIsNull() {
            addCriterion("product_blade is null");
            return (Criteria) this;
        }

        public Criteria andProductBladeIsNotNull() {
            addCriterion("product_blade is not null");
            return (Criteria) this;
        }

        public Criteria andProductBladeEqualTo(String value) {
            addCriterion("product_blade =", value, "productBlade");
            return (Criteria) this;
        }

        public Criteria andProductBladeNotEqualTo(String value) {
            addCriterion("product_blade <>", value, "productBlade");
            return (Criteria) this;
        }

        public Criteria andProductBladeGreaterThan(String value) {
            addCriterion("product_blade >", value, "productBlade");
            return (Criteria) this;
        }

        public Criteria andProductBladeGreaterThanOrEqualTo(String value) {
            addCriterion("product_blade >=", value, "productBlade");
            return (Criteria) this;
        }

        public Criteria andProductBladeLessThan(String value) {
            addCriterion("product_blade <", value, "productBlade");
            return (Criteria) this;
        }

        public Criteria andProductBladeLessThanOrEqualTo(String value) {
            addCriterion("product_blade <=", value, "productBlade");
            return (Criteria) this;
        }

        public Criteria andProductBladeLike(String value) {
            addCriterion("product_blade like", value, "productBlade");
            return (Criteria) this;
        }

        public Criteria andProductBladeNotLike(String value) {
            addCriterion("product_blade not like", value, "productBlade");
            return (Criteria) this;
        }

        public Criteria andProductBladeIn(List<String> values) {
            addCriterion("product_blade in", values, "productBlade");
            return (Criteria) this;
        }

        public Criteria andProductBladeNotIn(List<String> values) {
            addCriterion("product_blade not in", values, "productBlade");
            return (Criteria) this;
        }

        public Criteria andProductBladeBetween(String value1, String value2) {
            addCriterion("product_blade between", value1, value2, "productBlade");
            return (Criteria) this;
        }

        public Criteria andProductBladeNotBetween(String value1, String value2) {
            addCriterion("product_blade not between", value1, value2, "productBlade");
            return (Criteria) this;
        }

        public Criteria andProductPillarIsNull() {
            addCriterion("product_pillar is null");
            return (Criteria) this;
        }

        public Criteria andProductPillarIsNotNull() {
            addCriterion("product_pillar is not null");
            return (Criteria) this;
        }

        public Criteria andProductPillarEqualTo(String value) {
            addCriterion("product_pillar =", value, "productPillar");
            return (Criteria) this;
        }

        public Criteria andProductPillarNotEqualTo(String value) {
            addCriterion("product_pillar <>", value, "productPillar");
            return (Criteria) this;
        }

        public Criteria andProductPillarGreaterThan(String value) {
            addCriterion("product_pillar >", value, "productPillar");
            return (Criteria) this;
        }

        public Criteria andProductPillarGreaterThanOrEqualTo(String value) {
            addCriterion("product_pillar >=", value, "productPillar");
            return (Criteria) this;
        }

        public Criteria andProductPillarLessThan(String value) {
            addCriterion("product_pillar <", value, "productPillar");
            return (Criteria) this;
        }

        public Criteria andProductPillarLessThanOrEqualTo(String value) {
            addCriterion("product_pillar <=", value, "productPillar");
            return (Criteria) this;
        }

        public Criteria andProductPillarLike(String value) {
            addCriterion("product_pillar like", value, "productPillar");
            return (Criteria) this;
        }

        public Criteria andProductPillarNotLike(String value) {
            addCriterion("product_pillar not like", value, "productPillar");
            return (Criteria) this;
        }

        public Criteria andProductPillarIn(List<String> values) {
            addCriterion("product_pillar in", values, "productPillar");
            return (Criteria) this;
        }

        public Criteria andProductPillarNotIn(List<String> values) {
            addCriterion("product_pillar not in", values, "productPillar");
            return (Criteria) this;
        }

        public Criteria andProductPillarBetween(String value1, String value2) {
            addCriterion("product_pillar between", value1, value2, "productPillar");
            return (Criteria) this;
        }

        public Criteria andProductPillarNotBetween(String value1, String value2) {
            addCriterion("product_pillar not between", value1, value2, "productPillar");
            return (Criteria) this;
        }

        public Criteria andProductMotorIsNull() {
            addCriterion("product_motor is null");
            return (Criteria) this;
        }

        public Criteria andProductMotorIsNotNull() {
            addCriterion("product_motor is not null");
            return (Criteria) this;
        }

        public Criteria andProductMotorEqualTo(String value) {
            addCriterion("product_motor =", value, "productMotor");
            return (Criteria) this;
        }

        public Criteria andProductMotorNotEqualTo(String value) {
            addCriterion("product_motor <>", value, "productMotor");
            return (Criteria) this;
        }

        public Criteria andProductMotorGreaterThan(String value) {
            addCriterion("product_motor >", value, "productMotor");
            return (Criteria) this;
        }

        public Criteria andProductMotorGreaterThanOrEqualTo(String value) {
            addCriterion("product_motor >=", value, "productMotor");
            return (Criteria) this;
        }

        public Criteria andProductMotorLessThan(String value) {
            addCriterion("product_motor <", value, "productMotor");
            return (Criteria) this;
        }

        public Criteria andProductMotorLessThanOrEqualTo(String value) {
            addCriterion("product_motor <=", value, "productMotor");
            return (Criteria) this;
        }

        public Criteria andProductMotorLike(String value) {
            addCriterion("product_motor like", value, "productMotor");
            return (Criteria) this;
        }

        public Criteria andProductMotorNotLike(String value) {
            addCriterion("product_motor not like", value, "productMotor");
            return (Criteria) this;
        }

        public Criteria andProductMotorIn(List<String> values) {
            addCriterion("product_motor in", values, "productMotor");
            return (Criteria) this;
        }

        public Criteria andProductMotorNotIn(List<String> values) {
            addCriterion("product_motor not in", values, "productMotor");
            return (Criteria) this;
        }

        public Criteria andProductMotorBetween(String value1, String value2) {
            addCriterion("product_motor between", value1, value2, "productMotor");
            return (Criteria) this;
        }

        public Criteria andProductMotorNotBetween(String value1, String value2) {
            addCriterion("product_motor not between", value1, value2, "productMotor");
            return (Criteria) this;
        }

        public Criteria andProductCupIsNull() {
            addCriterion("product_cup is null");
            return (Criteria) this;
        }

        public Criteria andProductCupIsNotNull() {
            addCriterion("product_cup is not null");
            return (Criteria) this;
        }

        public Criteria andProductCupEqualTo(String value) {
            addCriterion("product_cup =", value, "productCup");
            return (Criteria) this;
        }

        public Criteria andProductCupNotEqualTo(String value) {
            addCriterion("product_cup <>", value, "productCup");
            return (Criteria) this;
        }

        public Criteria andProductCupGreaterThan(String value) {
            addCriterion("product_cup >", value, "productCup");
            return (Criteria) this;
        }

        public Criteria andProductCupGreaterThanOrEqualTo(String value) {
            addCriterion("product_cup >=", value, "productCup");
            return (Criteria) this;
        }

        public Criteria andProductCupLessThan(String value) {
            addCriterion("product_cup <", value, "productCup");
            return (Criteria) this;
        }

        public Criteria andProductCupLessThanOrEqualTo(String value) {
            addCriterion("product_cup <=", value, "productCup");
            return (Criteria) this;
        }

        public Criteria andProductCupLike(String value) {
            addCriterion("product_cup like", value, "productCup");
            return (Criteria) this;
        }

        public Criteria andProductCupNotLike(String value) {
            addCriterion("product_cup not like", value, "productCup");
            return (Criteria) this;
        }

        public Criteria andProductCupIn(List<String> values) {
            addCriterion("product_cup in", values, "productCup");
            return (Criteria) this;
        }

        public Criteria andProductCupNotIn(List<String> values) {
            addCriterion("product_cup not in", values, "productCup");
            return (Criteria) this;
        }

        public Criteria andProductCupBetween(String value1, String value2) {
            addCriterion("product_cup between", value1, value2, "productCup");
            return (Criteria) this;
        }

        public Criteria andProductCupNotBetween(String value1, String value2) {
            addCriterion("product_cup not between", value1, value2, "productCup");
            return (Criteria) this;
        }

        public Criteria andProductSwitchIsNull() {
            addCriterion("product_switch is null");
            return (Criteria) this;
        }

        public Criteria andProductSwitchIsNotNull() {
            addCriterion("product_switch is not null");
            return (Criteria) this;
        }

        public Criteria andProductSwitchEqualTo(String value) {
            addCriterion("product_switch =", value, "productSwitch");
            return (Criteria) this;
        }

        public Criteria andProductSwitchNotEqualTo(String value) {
            addCriterion("product_switch <>", value, "productSwitch");
            return (Criteria) this;
        }

        public Criteria andProductSwitchGreaterThan(String value) {
            addCriterion("product_switch >", value, "productSwitch");
            return (Criteria) this;
        }

        public Criteria andProductSwitchGreaterThanOrEqualTo(String value) {
            addCriterion("product_switch >=", value, "productSwitch");
            return (Criteria) this;
        }

        public Criteria andProductSwitchLessThan(String value) {
            addCriterion("product_switch <", value, "productSwitch");
            return (Criteria) this;
        }

        public Criteria andProductSwitchLessThanOrEqualTo(String value) {
            addCriterion("product_switch <=", value, "productSwitch");
            return (Criteria) this;
        }

        public Criteria andProductSwitchLike(String value) {
            addCriterion("product_switch like", value, "productSwitch");
            return (Criteria) this;
        }

        public Criteria andProductSwitchNotLike(String value) {
            addCriterion("product_switch not like", value, "productSwitch");
            return (Criteria) this;
        }

        public Criteria andProductSwitchIn(List<String> values) {
            addCriterion("product_switch in", values, "productSwitch");
            return (Criteria) this;
        }

        public Criteria andProductSwitchNotIn(List<String> values) {
            addCriterion("product_switch not in", values, "productSwitch");
            return (Criteria) this;
        }

        public Criteria andProductSwitchBetween(String value1, String value2) {
            addCriterion("product_switch between", value1, value2, "productSwitch");
            return (Criteria) this;
        }

        public Criteria andProductSwitchNotBetween(String value1, String value2) {
            addCriterion("product_switch not between", value1, value2, "productSwitch");
            return (Criteria) this;
        }

        public Criteria andProductStockIsNull() {
            addCriterion("product_stock is null");
            return (Criteria) this;
        }

        public Criteria andProductStockIsNotNull() {
            addCriterion("product_stock is not null");
            return (Criteria) this;
        }

        public Criteria andProductStockEqualTo(BigDecimal value) {
            addCriterion("product_stock =", value, "productStock");
            return (Criteria) this;
        }

        public Criteria andProductStockNotEqualTo(BigDecimal value) {
            addCriterion("product_stock <>", value, "productStock");
            return (Criteria) this;
        }

        public Criteria andProductStockGreaterThan(BigDecimal value) {
            addCriterion("product_stock >", value, "productStock");
            return (Criteria) this;
        }

        public Criteria andProductStockGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("product_stock >=", value, "productStock");
            return (Criteria) this;
        }

        public Criteria andProductStockLessThan(BigDecimal value) {
            addCriterion("product_stock <", value, "productStock");
            return (Criteria) this;
        }

        public Criteria andProductStockLessThanOrEqualTo(BigDecimal value) {
            addCriterion("product_stock <=", value, "productStock");
            return (Criteria) this;
        }

        public Criteria andProductStockIn(List<BigDecimal> values) {
            addCriterion("product_stock in", values, "productStock");
            return (Criteria) this;
        }

        public Criteria andProductStockNotIn(List<BigDecimal> values) {
            addCriterion("product_stock not in", values, "productStock");
            return (Criteria) this;
        }

        public Criteria andProductStockBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("product_stock between", value1, value2, "productStock");
            return (Criteria) this;
        }

        public Criteria andProductStockNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("product_stock not between", value1, value2, "productStock");
            return (Criteria) this;
        }

        public Criteria andProductPriceIsNull() {
            addCriterion("product_price is null");
            return (Criteria) this;
        }

        public Criteria andProductPriceIsNotNull() {
            addCriterion("product_price is not null");
            return (Criteria) this;
        }

        public Criteria andProductPriceEqualTo(BigDecimal value) {
            addCriterion("product_price =", value, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceNotEqualTo(BigDecimal value) {
            addCriterion("product_price <>", value, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceGreaterThan(BigDecimal value) {
            addCriterion("product_price >", value, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("product_price >=", value, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceLessThan(BigDecimal value) {
            addCriterion("product_price <", value, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("product_price <=", value, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceIn(List<BigDecimal> values) {
            addCriterion("product_price in", values, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceNotIn(List<BigDecimal> values) {
            addCriterion("product_price not in", values, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("product_price between", value1, value2, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("product_price not between", value1, value2, "productPrice");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNull() {
            addCriterion("update_user is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNotNull() {
            addCriterion("update_user is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserEqualTo(String value) {
            addCriterion("update_user =", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotEqualTo(String value) {
            addCriterion("update_user <>", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThan(String value) {
            addCriterion("update_user >", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThanOrEqualTo(String value) {
            addCriterion("update_user >=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThan(String value) {
            addCriterion("update_user <", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThanOrEqualTo(String value) {
            addCriterion("update_user <=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLike(String value) {
            addCriterion("update_user like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotLike(String value) {
            addCriterion("update_user not like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIn(List<String> values) {
            addCriterion("update_user in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotIn(List<String> values) {
            addCriterion("update_user not in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserBetween(String value1, String value2) {
            addCriterion("update_user between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotBetween(String value1, String value2) {
            addCriterion("update_user not between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("update_date is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("update_date is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(String value) {
            addCriterion("update_date =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(String value) {
            addCriterion("update_date <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(String value) {
            addCriterion("update_date >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(String value) {
            addCriterion("update_date >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(String value) {
            addCriterion("update_date <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(String value) {
            addCriterion("update_date <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLike(String value) {
            addCriterion("update_date like", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotLike(String value) {
            addCriterion("update_date not like", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<String> values) {
            addCriterion("update_date in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<String> values) {
            addCriterion("update_date not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(String value1, String value2) {
            addCriterion("update_date between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(String value1, String value2) {
            addCriterion("update_date not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(String value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(String value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(String value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(String value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(String value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLike(String value) {
            addCriterion("update_time like", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotLike(String value) {
            addCriterion("update_time not like", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<String> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<String> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(String value1, String value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(String value1, String value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbggenerated do_not_delete_during_merge Fri Jul 30 21:01:06 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbggenerated Fri Jul 30 21:01:06 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}